name: DunceChat
version: '${version}'
main: gg.corn.DunceChat.DunceChat
api-version: '1.21'
softdepend:
  - PlaceholderAPI
commands:
  duncemigrate:
    description: Migrate from old schema to new schema
    usage: /duncemigrate
    permission: duncechat.admin
  dunce:
    usage: /dunce <player> <duration> <reason>
    description: Central command for managing rule-breaking players.
    permission: duncechat.admin
  duncechat:
    usage: /duncechat <message>
    aliases: [dc]
    description: Send a message in Dunce Chat
  clearchat:
    usage: /clearchat
    description: Clear the chat
    permission: duncechat.admin
  dcoff:
    usage: /dcoff
    description: Hides the Unmoderated Chat.
  dcon:
    usage: /dcon
    description: Shows the Unmoderated Chat.
  undunce:
    usage: /undunce <player>
    description: Undunce a player.
    permission: duncechat.admin
  duncemenu:
    usage: /duncemenu
    description: Shows the DunceChat Menu.
  duncelookup:
    usage: /duncelookup <player>
    aliases: dl
    description: Look up details on a dunced player.
    permission: duncechat.admin
  duncereload:
    usage: /duncereload
    description: Reloads the configuration.
    permission: duncechat.admin
